---

- name: Setup macbook data analysis
  hosts: localhost

  tasks:
  - name: Install python & octave
    homebrew:
      name:
        - 'python'
        - 'octave'

  - name: Install python packages
    pip:
      name:
      - 'numpy'
      - 'pandas'
      - "pandas-datareader"
      - 'matplotlib'
      - 'jupyterlab'
      - 'jupytext'
      - 'py_vollib'
      - 'statsmodels'

  - name: Install R
    homebrew:
      name: r

  - name: Install RStudio
    homebrew_cask:
      name: rstudio

  # - name: Install r-packages
  #   shell: echo "install.packages('tseries', repos='https://cloud.r-project.org/')" | R --slave --no-save --no-restore-history
  #   with_items:
  #     - rstring
  #     - quantmod
  #     - tseries

