---

- name: Setup macbook data analysis
  hosts: localhost

  tasks:
  - name: Install python & octave
    homebrew:
      name:
        - 'python'
        - 'octave'

  - name: Install python packages
    pip:
      name:
      - 'numpy'
      - 'pandas'
      - "pandas-datareader"
      - 'matplotlib'
      - 'jupyterlab'
      - 'jupytext'
      - 'py_vollib'
